#! /bin/sh

export PATH="$PATH:$HOME/.config/bspwm/panel/"

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

PANEL_HEIGHT=50
PANEL_FONT="Fira Code-16"

bspc config top_padding $PANEL_HEIGHT
bspc subscribe > "$PANEL_FIFO" &

xtitle -sf 'T%s' > "$PANEL_FIFO" &
conky -c ~/.config/bspwm/panel/conkyrc > "$PANEL_FIFO" &

source ~/.config/bspwm/panel/panel_colors

cat "$PANEL_FIFO" | $HOME/.config/bspwm/panel/panel_bar | lemonbar -g x$PANEL_HEIGHT -f "$PANEL_FONT" -f "$PANEL_FONT_ICONS" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" &

wait
