#! /bin/sh

bspc config border_width        1
bspc config window_gap         0

bspc config split_ratio         0.6
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config presel_feedback_color "#222222"

bspc monitor -d 1 2 3 4 5 6

/home/jw/.config/bspwm/panel/panel &
