#! /bin/sh

bspc monitor -d 1 2 3 4 5 6

bspc config border_width        2
bspc config window_gap          5
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc rule -a Gimp desktop=^6 follow=on floating=on
bspc rule -a Steam desktop=^2
bspc rule -a mathematica desktop=^2
#bspc rule -a urxvt floating=on
# bspc rule -a mplayer2 floating=on
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

#/home/jw/Code/scripts/facebook.rb &
#/home/jw/Code/scripts/gmail.py &
/home/jw/.config/bspwm/panel/panel &
